/*
 * This source file was generated by the Gradle 'init' task
 */
package week8labactivity;

import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

class AppTest { 
    @Test
    void testAppHasAGreeting() {
        // Contoh pengetesan sederhana
        assertTrue(true, "Pesan ini akan muncul jika test gagal");
    }
}

